# this file is a settings file.

Lores: 1

treasure1:
  LoreLines: 4
  1: "§fこれを手に入れたあなたはラッキー!!"
  2: "§f設置するとお宝が手に入るかも!!"
  3: ""
  4: "§fPublicServer 2022"

treasureDropWarn: "§cYour inventory is full. \nSo a treasure chest that you get, could not add your inventory.\nThe treasure chest was dropped on the ground."

stairs: 0
ores: 0
slabs: 0
logs: 0
commons: 0
dangerous: 0